# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
 build:
    desc: Build binary
    cmds:
      - ./scripts/build.sh -s ~/pingpong/main.go
 package:
    desc: To create a package
    cmds:
      - ./scripts/package.sh -n ${DIRECTORY} --rpm -s ~/pingpong/main -v 0.2.0
#  package-sync:

