# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
 build:
    cmds:
      - ./scripts/build.sh {{.CLI_ARGS}} 
 package:
    cmds:
      - ./scripts/package.sh {{.CLI_ARGS}}
 package-sync:
    cmds:
      - ./scripts/package-sync.sh {{.CLI_ARGS}}
