# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
 build:
    desc: Build binary
    cmds:
      - ./scripts/build.sh
#  package:
#  package-sync:

